services:
  postgres_db:
    image: postgres:16
    environment:
      POSTGRES_USER: herrera_jordy
      POSTGRES_PASSWORD: Jherrera2412
      POSTGRES_DB: herrera_jordy_persistencia
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      
volumes:
  postgres_data:
